/**
 * 图标自动化生成管线
 *
 * 完整流程: svg/ 目录下的 SVG 文件 → src/icons/ 下的 Vue 组件 → index.ts 导出
 *
 * 用法:
 *   pnpm generate              # 从 SVG 生成 Vue 组件 + index.ts
 *
 * 设计师只需要:
 *   1. 将 SVG 文件放入 svg/ 目录（命名: kebab-case，如 arrow-left.svg）
 *   2. 执行 pnpm generate
 *   3. 自动得到 IconArrowLeft 组件并导出
 *
 * 命名规则:
 *   svg 文件名 (kebab-case) → Vue 组件名 (PascalCase)
 *   arrow-left.svg  → ArrowLeft.vue  → export as IconArrowLeft
 *   close.svg       → Close.vue      → export as IconClose
 */
import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { resolve, basename } from 'path';
import { optimize, type Config as SvgoConfig } from 'svgo';

const SVG_DIR = resolve(__dirname, '../svg');
const ICONS_DIR = resolve(__dirname, '../src/icons');
const OUTPUT_FILE = resolve(__dirname, '../index.ts');

/** SVGO 优化配置 */
const svgoConfig: SvgoConfig = {
  plugins: [
    // 使用默认预设优化
    'preset-default',
    // 移除 SVG 上的宽高属性，由 IconWrapper 控制尺寸
    'removeDimensions',
    // 将 style 属性转为 presentation attributes
    'convertStyleToAttrs',
    // 移除无用的填充色（统一由 currentColor 控制）
    {
      name: 'removeAttrs',
      params: { attrs: ['fill'] },
    },
  ],
};

/** 使用 SVGO 优化 SVG 内容 */
function optimizeSvg(raw: string, filename: string): string {
  const result = optimize(raw, { ...svgoConfig, path: filename });
  return result.data;
}

/** kebab-case → PascalCase: "arrow-left" → "ArrowLeft" */
function toPascalCase(str: string): string {
  return str
    .split('-')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

/** 从 SVG 文件内容中提取 <svg>...</svg> 的内部内容和属性 */
function parseSvg(content: string): { attrs: string; innerHTML: string } {
  // 提取 <svg ...>...</svg>
  const svgMatch = content.match(/<svg([^>]*)>([\s\S]*?)<\/svg>/);
  if (!svgMatch) {
    throw new Error('Invalid SVG content');
  }

  let attrs = svgMatch[1].trim();
  const innerHTML = svgMatch[2].trim();

  // 确保有 xmlns
  if (!attrs.includes('xmlns=')) {
    attrs += ' xmlns="http://www.w3.org/2000/svg"';
  }

  return { attrs, innerHTML };
}

/** 生成单个 Vue 图标组件内容 */
function generateVueComponent(name: string, svgContent: string): string {
  const { attrs, innerHTML } = parseSvg(svgContent);

  return `<template>
  <IconWrapper v-bind="$props">
    <svg ${attrs}>
      ${innerHTML}
    </svg>
  </IconWrapper>
</template>

<script setup lang="ts">
import IconWrapper from '../components/IconWrapper.vue';
import type { IconProps } from '../types';

defineOptions({
  name: 'Icon${name}',
});

defineProps<IconProps>();
</script>
`;
}

/** 生成 index.ts 导出文件 */
function generateIndex(names: string[]): string {
  const iconExports = names
    .sort()
    .map((name) => `export { default as Icon${name} } from './src/icons/${name}.vue';`);

  return [
    '// ⚠️ This file is auto-generated by scripts/generate.ts — DO NOT EDIT MANUALLY',
    '',
    '// Icon wrapper',
    "export { default as IconWrapper } from './src/components/IconWrapper.vue';",
    '',
    '// Icons',
    ...iconExports,
    '',
    '// Types',
    "export type { IconProps } from './src/types';",
    '',
  ].join('\n');
}

function main() {
  // 确保目录存在
  if (!existsSync(SVG_DIR)) {
    mkdirSync(SVG_DIR, { recursive: true });
    console.log(`📁 Created svg/ directory. Place your SVG files there.`);
    return;
  }

  if (!existsSync(ICONS_DIR)) {
    mkdirSync(ICONS_DIR, { recursive: true });
  }

  // 1. 扫描 SVG 文件
  const svgFiles = readdirSync(SVG_DIR)
    .filter((f) => f.endsWith('.svg'))
    .sort();

  if (svgFiles.length === 0) {
    console.log('⚠️  No SVG files found in svg/ directory');
    return;
  }

  // 2. 为每个 SVG 生成 Vue 组件
  const componentNames: string[] = [];

  for (const file of svgFiles) {
    const kebabName = basename(file, '.svg'); // e.g. "arrow-left"
    const pascalName = toPascalCase(kebabName); // e.g. "ArrowLeft"
    const rawSvg = readFileSync(resolve(SVG_DIR, file), 'utf-8');

    // SVGO 优化
    const optimizedSvg = optimizeSvg(rawSvg, file);
    const saved = ((1 - optimizedSvg.length / rawSvg.length) * 100).toFixed(1);

    const vueContent = generateVueComponent(pascalName, optimizedSvg);
    const vueFilePath = resolve(ICONS_DIR, `${pascalName}.vue`);

    writeFileSync(vueFilePath, vueContent, 'utf-8');
    componentNames.push(pascalName);

    console.log(`  ✅ ${file} → Icon${pascalName}  (${rawSvg.length}B → ${optimizedSvg.length}B, -${saved}%)`);
  }

  // 3. 生成 index.ts
  const indexContent = generateIndex(componentNames);
  writeFileSync(OUTPUT_FILE, indexContent, 'utf-8');

  console.log(`\n🎉 Generated ${componentNames.length} icon components + index.ts`);
}

main();
