// ⚠️ This file is auto-generated by scripts/generate.ts — DO NOT EDIT MANUALLY

// Icon wrapper
export { default as IconWrapper } from './src/components/IconWrapper.vue';

// Icons
export { default as IconArrowLeft } from './src/icons/ArrowLeft.vue';
export { default as IconArrowRight } from './src/icons/ArrowRight.vue';
export { default as IconCheck } from './src/icons/Check.vue';
export { default as IconClose } from './src/icons/Close.vue';

// Types
export type { IconProps } from './src/types';
