// ⚠️ This file is auto-generated by scripts/generate.ts — DO NOT EDIT MANUALLY

import type { Component } from 'vue';

// Icon wrapper
export { default as IconWrapper } from './src/components/IconWrapper.vue';

// Icons
import IconArrowDown from './src/icons/ArrowDown.vue';
import IconArrowLeft from './src/icons/ArrowLeft.vue';
import IconArrowRight from './src/icons/ArrowRight.vue';
import IconArrowUp from './src/icons/ArrowUp.vue';
import IconCheck from './src/icons/Check.vue';
import IconClose from './src/icons/Close.vue';
import IconEye from './src/icons/Eye.vue';
import IconEyeOff from './src/icons/EyeOff.vue';
import IconInfoFilled from './src/icons/InfoFilled.vue';
import IconQuestionFilled from './src/icons/QuestionFilled.vue';
import IconWarningFilled from './src/icons/WarningFilled.vue';

export {
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconCheck,
  IconClose,
  IconEye,
  IconEyeOff,
  IconInfoFilled,
  IconQuestionFilled,
  IconWarningFilled,
};

// Icon name → Component map
export const iconMap: Record<string, Component> = {
  'arrow-down': IconArrowDown,
  'arrow-left': IconArrowLeft,
  'arrow-right': IconArrowRight,
  'arrow-up': IconArrowUp,
  check: IconCheck,
  close: IconClose,
  eye: IconEye,
  'eye-off': IconEyeOff,
  'info-filled': IconInfoFilled,
  'question-filled': IconQuestionFilled,
  'warning-filled': IconWarningFilled,
};

// Types
export type { IconProps } from './src/types';
